CREATE TABLE IF NOT EXISTS ab_dispatches (
  dispatch_id int NOT NULL AUTO_INCREMENT,
  company_id int NOT NULL,
  order_id int NOT NULL,
  customer_id int NOT NULL,
  dispatch_no varchar(50) NOT NULL,
  dispatch_date date NOT NULL,
  transporter_name varchar(150) DEFAULT NULL,
  vehicle_no varchar(50) DEFAULT NULL,
  driver_name varchar(150) DEFAULT NULL,
  driver_mobile varchar(20) DEFAULT NULL,
  lr_no varchar(80) DEFAULT NULL,
  invoice_no varchar(80) DEFAULT NULL,
  delivery_location text DEFAULT NULL,
  dispatch_status varchar(50) NOT NULL DEFAULT 'dispatched',
  remarks text DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by int DEFAULT NULL,
  modified_date datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status enum('active','inactive','delete') NOT NULL DEFAULT 'active',
  PRIMARY KEY (dispatch_id),
  UNIQUE KEY uk_ab_dispatch_no_company (company_id, dispatch_no),
  KEY idx_ab_dispatch_order (order_id),
  KEY idx_ab_dispatch_customer (customer_id),
  KEY idx_ab_dispatch_company_status (company_id, dispatch_status, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ab_dispatch_items (
  dispatch_item_id int NOT NULL AUTO_INCREMENT,
  company_id int NOT NULL,
  dispatch_id int NOT NULL,
  order_id int NOT NULL,
  order_item_id int NOT NULL,
  product_id int NOT NULL,
  ready_qty decimal(15,2) NOT NULL DEFAULT 0,
  already_dispatched_qty decimal(15,2) NOT NULL DEFAULT 0,
  available_qty decimal(15,2) NOT NULL DEFAULT 0,
  dispatch_qty decimal(15,2) NOT NULL DEFAULT 0,
  pending_after_dispatch_qty decimal(15,2) NOT NULL DEFAULT 0,
  item_dispatch_status varchar(50) NOT NULL DEFAULT 'pending',
  remarks text DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by int DEFAULT NULL,
  modified_date datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  status enum('active','inactive','delete') NOT NULL DEFAULT 'active',
  PRIMARY KEY (dispatch_item_id),
  KEY idx_ab_dispatch_items_dispatch (dispatch_id),
  KEY idx_ab_dispatch_items_order_item (order_item_id),
  KEY idx_ab_dispatch_items_order (order_id),
  KEY idx_ab_dispatch_items_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ab_dispatch_history (
  history_id int NOT NULL AUTO_INCREMENT,
  company_id int NOT NULL,
  dispatch_id int NOT NULL,
  order_id int NOT NULL,
  old_status varchar(50) DEFAULT NULL,
  new_status varchar(50) NOT NULL,
  changed_by int DEFAULT NULL,
  changed_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note text DEFAULT NULL,
  PRIMARY KEY (history_id),
  KEY idx_ab_dispatch_history_dispatch (dispatch_id),
  KEY idx_ab_dispatch_history_order (order_id),
  KEY idx_ab_dispatch_history_company (company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;